# **Support** **Vector** **Machine** 

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# importing important libraries
import numpy as np 
import pandas as pd
import random 
random.seed(3)

In [16]:
df3=pd.read_csv("/content/drive/MyDrive/df3_final.csv")    # Importing data from Directory
df3.head()

lesion_id      image_id   dx dx_type   age   sex localization  Pixel_0  \
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp      187   
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp       25   
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp      146   
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp       27   
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear      134   

   Pixel_1  Pixel_2  ...  Pixel_3063  Pixel_3064  Pixel_3065  Pixel_3066  \
0      148      190  ...         154         132         178         167   
1       14       23  ...          43          26          42          27   
2      133      186  ...         143         128         160         139   
3       16       31  ...          22          16          29          16   
4      110      153  ...         179         161         202         132   

   Pixel_3067  Pixel_3068  Pixel_3069  Pixel_3070  Pixel_3071  label  
0         150         183         177         153         185      2  
1          14          24          28          15          25      2  
2         117         151         116         105         134      2  
3          12          26          16          12          24      2  
4         122         158          84          69         101      2  

[5 rows x 3080 columns]

In [17]:
X = df3.iloc[:,7:3079].values
y = df3.iloc[:, 3079].values

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix,classification_report

In [19]:
Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.20,random_state=30)    #split data into training and testing group

# **Linear Kernal**

In [20]:
classifier_linear = SVC(kernel='linear')      #fit to the training data
classifier_linear.fit(Xtr,ytr)

SVC(kernel='linear')

In [21]:
 y_pred = classifier_linear.predict(Xte)

In [22]:
print('accuracy: %f' % ( np.mean(y_pred == yte) )) 
# Accuracy of the model

accuracy: 0.599601


In [23]:
print(confusion_matrix(yte,y_pred))

[[ 17  12  11   4   1  17   3]
 [ 18  42  11   1   4  29   6]
 [ 16  19  73   6  23  74   1]
 [  3   7   5   5   3   1   0]
 [ 10  17  41   3  54  95   5]
 [ 23  21 139  10 143 999   4]
 [  1   6   0   0   1   8  11]]


In [24]:
print(classification_report(yte,y_pred))


              precision    recall  f1-score   support

           0       0.19      0.26      0.22        65
           1       0.34      0.38      0.36       111
           2       0.26      0.34      0.30       212
           3       0.17      0.21      0.19        24
           4       0.24      0.24      0.24       225
           5       0.82      0.75      0.78      1339
           6       0.37      0.41      0.39        27

    accuracy                           0.60      2003
   macro avg       0.34      0.37      0.35      2003
weighted avg       0.63      0.60      0.61      2003



# **Polynomial Kernel**


In [25]:
classifier_poly1 =SVC(kernel='poly',degree=2)  #fit to the training data
classifier_poly1.fit(Xtr,ytr)

SVC(degree=2, kernel='poly')

In [26]:
y_pred_poly1 = classifier_poly1.predict(Xte)

In [27]:
print('accuracy: %f' % ( np.mean(y_pred_poly1 == yte) ))
print(confusion_matrix(yte,y_pred_poly1))
print(classification_report(yte,y_pred_poly1))

accuracy: 0.710934
[[  15   14    9    1    2   23    1]
 [   8   47    9    1    1   41    4]
 [   7   12   76    0   11  106    0]
 [   5    9    4    1    0    5    0]
 [  10    9   26    0   29  148    3]
 [   7    9   45    2   32 1243    1]
 [   2    4    0    0    0    8   13]]
              precision    recall  f1-score   support

           0       0.28      0.23      0.25        65
           1       0.45      0.42      0.44       111
           2       0.45      0.36      0.40       212
           3       0.20      0.04      0.07        24
           4       0.39      0.13      0.19       225
           5       0.79      0.93      0.85      1339
           6       0.59      0.48      0.53        27

    accuracy                           0.71      2003
   macro avg       0.45      0.37      0.39      2003
weighted avg       0.66      0.71      0.67      2003



# **Radial basis function kernel**

In [28]:
classifier_rbf =SVC(kernel='rbf')      #fit to the training data
classifier_rbf.fit(Xtr,ytr)

SVC()

In [29]:
 y_pred_rbf = classifier_rbf.predict(Xte)

In [30]:
print('accuracy: %f' % ( np.mean(y_pred_rbf== yte) ))
print(confusion_matrix(yte,y_pred_rbf))
print(classification_report(yte,y_pred_rbf))

accuracy: 0.702946
[[   5   11   12    0    1   36    0]
 [   1   29   10    0    0   71    0]
 [   1    8   55    0    9  139    0]
 [   0    6    6    0    0   12    0]
 [   0    0   25    0   18  182    0]
 [   2    2   26    0    8 1301    0]
 [   0    5    3    0    0   19    0]]
              precision    recall  f1-score   support

           0       0.56      0.08      0.14        65
           1       0.48      0.26      0.34       111
           2       0.40      0.26      0.32       212
           3       0.00      0.00      0.00        24
           4       0.50      0.08      0.14       225
           5       0.74      0.97      0.84      1339
           6       0.00      0.00      0.00        27

    accuracy                           0.70      2003
   macro avg       0.38      0.24      0.25      2003
weighted avg       0.64      0.70      0.63      2003



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Sigmoid Kernel**


In [31]:
classifier_sigmoid = SVC(kernel='sigmoid')    #fit to the training data
classifier_sigmoid.fit(Xtr,ytr)

SVC(kernel='sigmoid')

In [32]:
y_pred_sigmoid = classifier_sigmoid.predict(Xte)

In [33]:
print('accuracy: %f' % ( np.mean(y_pred_sigmoid== yte) ))
print(confusion_matrix(yte,y_pred_sigmoid))
print(classification_report(yte,y_pred_sigmoid))

accuracy: 0.668497
[[   0    0    0    0    0   65    0]
 [   0    0    0    0    0  111    0]
 [   0    0    0    0    0  212    0]
 [   0    0    0    0    0   24    0]
 [   0    0    0    0    0  225    0]
 [   0    0    0    0    0 1339    0]
 [   0    0    0    0    0   27    0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        65
           1       0.00      0.00      0.00       111
           2       0.00      0.00      0.00       212
           3       0.00      0.00      0.00        24
           4       0.00      0.00      0.00       225
           5       0.67      1.00      0.80      1339
           6       0.00      0.00      0.00        27

    accuracy                           0.67      2003
   macro avg       0.10      0.14      0.11      2003
weighted avg       0.45      0.67      0.54      2003



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
